require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe Admin::BrewBatchesController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # BrewBatch. As you add validations to BrewBatch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {serial_number: "BG19-30", name: "Nadines Nonnenbräu"}
  end

  let(:invalid_attributes) do
    {serial_number: nil, name: "Brauzeugen Amber"}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BrewBatchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before do
    @request.env["HTTP_AUTHORIZATION"] = "Basic #{Base64.encode64("admin:")}"
  end

  describe "GET #index" do
    it "returns a success response" do
      BrewBatch.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      brew_batch = BrewBatch.create! valid_attributes
      get :edit, params: {id: brew_batch.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new BrewBatch" do
        expect do
          post :create, params: {brew_batch: valid_attributes}, session: valid_session
        end.to change(BrewBatch, :count).by(1)
      end

      it "redirects to the created brew_batch" do
        post :create, params: {brew_batch: valid_attributes}, session: valid_session
        expect(response).to redirect_to(admin_brew_batches_url)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {brew_batch: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) do
        {serial_number: "BG19-30", name: "Ale 'o' World"}
      end

      it "updates the requested brew_batch" do
        brew_batch = BrewBatch.create! valid_attributes
        put :update, params: {id: brew_batch.to_param, brew_batch: new_attributes}, session: valid_session
        brew_batch.reload
        expect(brew_batch.name).to eq("Ale 'o' World")
      end

      it "redirects to the brew_batch" do
        brew_batch = BrewBatch.create! valid_attributes
        put :update, params: {id: brew_batch.to_param, brew_batch: valid_attributes}, session: valid_session
        expect(response).to redirect_to(admin_brew_batches_url)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        brew_batch = BrewBatch.create! valid_attributes
        put :update, params: {id: brew_batch.to_param, brew_batch: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested brew_batch" do
      brew_batch = BrewBatch.create! valid_attributes
      expect do
        delete :destroy, params: {id: brew_batch.to_param}, session: valid_session
      end.to change(BrewBatch, :count).by(-1)
    end

    it "redirects to the brew_batches list" do
      brew_batch = BrewBatch.create! valid_attributes
      delete :destroy, params: {id: brew_batch.to_param}, session: valid_session
      expect(response).to redirect_to(admin_brew_batches_url)
    end
  end
end
